In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('customers.csv')  # dataset loading

In [4]:
df

,id,name,segment,state,city
0,CG-12520,Claire Gute,Consumer,Kentucky,Henderson
1,DV-13045,Darrin Van Huff,Corporate,California,Los Angeles
2,SO-20335,Sean O'Donnell,Consumer,Florida,Fort Lauderdale
3,BH-11710,Brosina Hoffman,Consumer,California,Los Angeles
4,AA-10480,Andrew Allen,Consumer,North Carolina,Concord
...,...,...,...,...,...
788,CJ-11875,Carl Jackson,Corporate,Pennsylvania,Philadelphia
789,RS-19870,Roy Skaria,Home Office,Iowa,Burlington
790,SC-20845,Sung Chung,Consumer,Illinois,Arlington Heights
791,RE-19405,Ricardo Emerson,Consumer,Ohio,Kent
792,SM-20905,Susan MacKendrick,Consumer,Ohio,Newark

In [5]:
# display first 5 rows
df.head(5)

         id             name    segment           state             city
0  CG-12520      Claire Gute   Consumer        Kentucky        Henderson
1  DV-13045  Darrin Van Huff  Corporate      California      Los Angeles
2  SO-20335   Sean O'Donnell   Consumer         Florida  Fort Lauderdale
3  BH-11710  Brosina Hoffman   Consumer      California      Los Angeles
4  AA-10480     Andrew Allen   Consumer  North Carolina          Concord

In [6]:
# display last 5 rows
df.tail(5)

           id               name      segment         state               city
788  CJ-11875       Carl Jackson    Corporate  Pennsylvania       Philadelphia
789  RS-19870         Roy Skaria  Home Office          Iowa         Burlington
790  SC-20845         Sung Chung     Consumer      Illinois  Arlington Heights
791  RE-19405    Ricardo Emerson     Consumer          Ohio               Kent
792  SM-20905  Susan MacKendrick     Consumer          Ohio             Newark

In [7]:
# check if there any null values
df.isnull()

        id   name  segment  state   city
0    False  False    False  False  False
1    False  False    False  False  False
2    False  False    False  False  False
3    False  False    False  False  False
4    False  False    False  False  False
..     ...    ...      ...    ...    ...
788  False  False    False  False  False
789  False  False    False  False  False
790  False  False    False  False  False
791  False  False    False  False  False
792  False  False    False  False  False

[793 rows x 5 columns]

In [8]:
# find total number of rows and columns
df.shape

(793, 5)

In [9]:
# print the column names
df.columns

Index(['id', 'name', 'segment', 'state', 'city'], dtype='str')

In [10]:
# check data types of each column
df.dtypes

id         str
name       str
segment    str
state      str
city       str
dtype: object

In [ ]:
# check if there any missing values
df.isnull().sum()

# or
# df.isna().sum()

id         0
name       0
segment    0
state      0
city       0
dtype: int64

In [12]:
# count number of unique states
df.state.nunique()
# or
# df['state'].nunique()

41

In [13]:
# count number of unique cities
df.city.nunique()

252

In [14]:
# count number of unique segments.
df.segment.nunique()

3

In [15]:
# display only name column
df.name

0            Claire Gute
1        Darrin Van Huff
2         Sean O'Donnell
3        Brosina Hoffman
4           Andrew Allen
             ...
788         Carl Jackson
789           Roy Skaria
790           Sung Chung
791      Ricardo Emerson
792    Susan MacKendrick
Name: name, Length: 793, dtype: str

In [16]:
# 11. Display name and state columns.

df[['name','state']]

                  name           state
0          Claire Gute        Kentucky
1      Darrin Van Huff      California
2       Sean O'Donnell         Florida
3      Brosina Hoffman      California
4         Andrew Allen  North Carolina
..                 ...             ...
788       Carl Jackson    Pennsylvania
789         Roy Skaria            Iowa
790         Sung Chung        Illinois
791    Ricardo Emerson            Ohio
792  Susan MacKendrick            Ohio

[793 rows x 2 columns]

In [17]:
# 12. Show all customers from California.
df.loc[df['state']=='California']

           id                name      segment       state           city
1    DV-13045     Darrin Van Huff    Corporate  California    Los Angeles
3    BH-11710     Brosina Hoffman     Consumer  California    Los Angeles
9    ZD-21925  Zuschuss Donatelli     Consumer  California  San Francisco
13   EH-13945       Eric Hoffmann     Consumer  California    Los Angeles
19   RA-19885        Ruben Ausman    Corporate  California    Los Angeles
..        ...                 ...          ...         ...            ...
770  DO-13645      Doug O'Connell     Consumer  California    Los Angeles
774  AO-10810   Anthony O'Donnell    Corporate  California    Los Angeles
778  VP-21760    Victoria Pisteka    Corporate  California  San Francisco
780  IM-15055       Ionia McGrath     Consumer  California      Roseville
786  BD-11560      Brendan Dodson  Home Office  California         Fresno

[161 rows x 5 columns]

In [18]:
# 13. Show all customers from Kentucky.
df.loc[df['state']=='Kentucky']

           id               name      segment     state           city
0    CG-12520        Claire Gute     Consumer  Kentucky      Henderson
213  DK-12985     Darren Koutras     Consumer  Kentucky      Henderson
232  BD-11725   Bruce Degenhardt     Consumer  Kentucky       Richmond
314  AF-10885         Art Foster     Consumer  Kentucky     Louisville
361  RD-19585           Rob Dowd     Consumer  Kentucky      Henderson
431  LP-17095          Liz Preis     Consumer  Kentucky         Murray
444  ND-18370  Natalie DeCherney     Consumer  Kentucky     Louisville
463  PW-19030     Pauline Webber    Corporate  Kentucky       Richmond
491  BO-11425      Bobby Odegard     Consumer  Kentucky       Richmond
542  KH-16330    Katharine Harms    Corporate  Kentucky  Bowling Green
631  BD-11635         Brian Derr     Consumer  Kentucky  Bowling Green
704  DH-13075      Dave Hallsten    Corporate  Kentucky       Richmond
776  SS-20515    Shirley Schmidt  Home Office  Kentucky     Louisville

In [19]:
# 14. Count customers in each segment. # use value.counts()
df['segment'].value_counts()

segment
Consumer       409
Corporate      236
Home Office    148
Name: count, dtype: int64

In [20]:
# 15. Find most frequent segment. use value.counts().idmax()
df['segment'].value_counts().idxmax()

'Consumer'

In [21]:
# 16. Find least frequent segment. use value.counts().idmin()
df['segment'].value_counts().idxmin()

'Home Office'

In [22]:
# 17. Sort dataset by name.
df.sort_values(by='name',ascending=True)

           id                name      segment           state           city
755  AB-10015       Aaron Bergman     Consumer      Washington        Seattle
692  AH-10030       Aaron Hawkins    Corporate    Pennsylvania   Philadelphia
442  AS-10045      Aaron Smayling    Corporate  North Carolina   Jacksonville
144  AB-10060     Adam Bellavance  Home Office        New York  New York City
340  AH-10075           Adam Hart    Corporate        New York  New York City
..        ...                 ...          ...             ...            ...
190  XP-21865        Xylona Preis     Consumer      California      San Diego
453  YS-21880       Yana Sorensen    Corporate  North Carolina     Burlington
289  YC-21895      Yoseph Carroll    Corporate      California  San Francisco
233  ZC-21910    Zuschuss Carroll     Consumer          Oregon          Salem
9    ZD-21925  Zuschuss Donatelli     Consumer      California  San Francisco

[793 rows x 5 columns]

In [23]:
# 18. Sort dataset by state.
df.sort_values(by='state',ascending=True)

           id             name    segment      state        city
662  CA-11965      Carol Adams  Corporate    Alabama      Hoover
584  RH-19600     Rob Haberlin   Consumer    Alabama  Huntsville
466  MC-17425     Mark Cousins  Corporate    Alabama      Mobile
699  EH-14185       Evan Henry   Consumer    Alabama     Decatur
562  AM-10705   Anne McFarland   Consumer    Alabama      Auburn
..        ...              ...        ...        ...         ...
7    PK-19075        Pete Kriz   Consumer  Wisconsin     Madison
214  BD-11500  Bradley Drucker   Consumer  Wisconsin   Green Bay
308  BW-11110     Bart Watters  Corporate  Wisconsin   Milwaukee
68   JE-16165   Justin Ellison  Corporate  Wisconsin    Franklin
532  RP-19855         Roy Phan  Corporate  Wisconsin     Kenosha

[793 rows x 5 columns]

In [24]:
# 21. Count customers per state. #value.counts()
df['state'].value_counts()

state
California              161
New York                 87
Texas                    77
Pennsylvania             50
Illinois                 41
Washington               38
Ohio                     38
North Carolina           30
Florida                  24
Arizona                  21
Colorado                 20
Georgia                  17
Michigan                 16
Virginia                 15
Kentucky                 13
Minnesota                13
Tennessee                13
Indiana                  12
New Jersey               10
Massachusetts            10
Wisconsin                 9
Alabama                   9
Connecticut               7
Utah                      6
Delaware                  6
Missouri                  6
Louisiana                 6
Rhode Island              5
Mississippi               5
New Mexico                4
Maryland                  4
Oregon                    3
Iowa                      3
Oklahoma                  3
Nebraska                  2
Nevada                    2
Arkansas                  2
New Hampshire             2
District of Columbia      1
Kansas                    1
South Dakota              1
Name: count, dtype: int64

In [25]:
# 22. Find top 5 states with maximum customers.
df['state'].value_counts().head(5)

state
California      161
New York         87
Texas            77
Pennsylvania     50
Illinois         41
Name: count, dtype: int64

In [26]:
# 23. Find state with minimum customers.
df['state'].value_counts().tail(1)

state
South Dakota    1
Name: count, dtype: int64

In [27]:
# 24. Count customers per city.
df['city'].value_counts()

city
New York City        68
Los Angeles          58
Philadelphia         46
San Francisco        41
Seattle              31
                     ..
Oklahoma City         1
Lehi                  1
Omaha                 1
Cranston              1
Arlington Heights     1
Name: count, Length: 252, dtype: int64