In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('customers.csv')  # dataset loading

In [4]:
df

,id,name,segment,state,city
0,CG-12520,Claire Gute,Consumer,Kentucky,Henderson
1,DV-13045,Darrin Van Huff,Corporate,California,Los Angeles
2,SO-20335,Sean O'Donnell,Consumer,Florida,Fort Lauderdale
3,BH-11710,Brosina Hoffman,Consumer,California,Los Angeles
4,AA-10480,Andrew Allen,Consumer,North Carolina,Concord
...,...,...,...,...,...
788,CJ-11875,Carl Jackson,Corporate,Pennsylvania,Philadelphia
789,RS-19870,Roy Skaria,Home Office,Iowa,Burlington
790,SC-20845,Sung Chung,Consumer,Illinois,Arlington Heights
791,RE-19405,Ricardo Emerson,Consumer,Ohio,Kent
792,SM-20905,Susan MacKendrick,Consumer,Ohio,Newark

In [5]:
# display first 5 rows
df.head(5)

         id             name    segment           state             city
0  CG-12520      Claire Gute   Consumer        Kentucky        Henderson
1  DV-13045  Darrin Van Huff  Corporate      California      Los Angeles
2  SO-20335   Sean O'Donnell   Consumer         Florida  Fort Lauderdale
3  BH-11710  Brosina Hoffman   Consumer      California      Los Angeles
4  AA-10480     Andrew Allen   Consumer  North Carolina          Concord

In [6]:
# display last 5 rows
df.tail(5)

           id               name      segment         state               city
788  CJ-11875       Carl Jackson    Corporate  Pennsylvania       Philadelphia
789  RS-19870         Roy Skaria  Home Office          Iowa         Burlington
790  SC-20845         Sung Chung     Consumer      Illinois  Arlington Heights
791  RE-19405    Ricardo Emerson     Consumer          Ohio               Kent
792  SM-20905  Susan MacKendrick     Consumer          Ohio             Newark

In [7]:
# check if there any null values
df.isnull()

        id   name  segment  state   city
0    False  False    False  False  False
1    False  False    False  False  False
2    False  False    False  False  False
3    False  False    False  False  False
4    False  False    False  False  False
..     ...    ...      ...    ...    ...
788  False  False    False  False  False
789  False  False    False  False  False
790  False  False    False  False  False
791  False  False    False  False  False
792  False  False    False  False  False

[793 rows x 5 columns]

In [8]:
# find total number of rows and columns
df.shape

(793, 5)

In [9]:
# print the column names
df.columns

Index(['id', 'name', 'segment', 'state', 'city'], dtype='str')

In [10]:
# check data types of each column
df.dtypes

id         str
name       str
segment    str
state      str
city       str
dtype: object

In [ ]:
# check if there any missing values
df.isnull().sum()

# or
# isna.sum()

id         0
name       0
segment    0
state      0
city       0
dtype: int64

In [12]:
# count number of unique states
df.state.nunique()
# or
# df['state'].nunique()

41

In [13]:
# count number of unique cities
df.city.nunique()

252

In [14]:
# count number of unique segments.
df.segment.nunique()

3

In [15]:
# display only name column
df.name

0            Claire Gute
1        Darrin Van Huff
2         Sean O'Donnell
3        Brosina Hoffman
4           Andrew Allen
             ...
788         Carl Jackson
789           Roy Skaria
790           Sung Chung
791      Ricardo Emerson
792    Susan MacKendrick
Name: name, Length: 793, dtype: str