In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Car Sales Missing Data.csv')

In [ ]:
df

       Make Colour  Odometer (KM)  Doors      Price
0    Nissan  Black        10148.0    4.0  Rs1366850
1    Toyota  White        10217.0    4.0  Rs1144150
2    Toyota  White        10247.0    4.0  Rs1628300
3     Honda  White        10953.0    4.0   Rs831800
4    Nissan   Blue        10954.0    4.0  Rs1521950
..      ...    ...            ...    ...        ...
995  Toyota  White            NaN    4.0  Rs1706650
996  Toyota  White            NaN    4.0  Rs1767900
997     BMW  White            NaN    5.0  Rs1906400
998  Toyota  White            NaN    4.0        NaN
999  Toyota  White            NaN    4.0        NaN

[1000 rows x 5 columns]

In [ ]:
df.isnull().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [ ]:
# drop
df1= df.copy()

In [ ]:
df1.dropna(ignore_index=True,inplace=True)
df1

       Make Colour  Odometer (KM)  Doors      Price
0    Nissan  Black        10148.0    4.0  Rs1366850
1    Toyota  White        10217.0    4.0  Rs1144150
2    Toyota  White        10247.0    4.0  Rs1628300
3     Honda  White        10953.0    4.0   Rs831800
4    Nissan   Blue        10954.0    4.0  Rs1521950
..      ...    ...            ...    ...        ...
768  Toyota   Blue       248447.0    4.0   Rs285400
769  Nissan  Black       248736.0    4.0   Rs417900
770  Toyota  White       248815.0    4.0   Rs489250
771   Honda   Blue       248899.0    4.0   Rs291700
772  Nissan   Blue       249860.0    4.0   Rs726200

[773 rows x 5 columns]

In [ ]:
df1.isnull().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [ ]:
# random

df2 = df.copy()

In [ ]:
df2['Make']=df2['Make'].fillna('Suzuki')
df2

       Make Colour  Odometer (KM)  Doors      Price
0    Nissan  Black        10148.0    4.0  Rs1366850
1    Toyota  White        10217.0    4.0  Rs1144150
2    Toyota  White        10247.0    4.0  Rs1628300
3     Honda  White        10953.0    4.0   Rs831800
4    Nissan   Blue        10954.0    4.0  Rs1521950
..      ...    ...            ...    ...        ...
995  Toyota  White            NaN    4.0  Rs1706650
996  Toyota  White            NaN    4.0  Rs1767900
997     BMW  White            NaN    5.0  Rs1906400
998  Toyota  White            NaN    4.0        NaN
999  Toyota  White            NaN    4.0        NaN

[1000 rows x 5 columns]

In [ ]:
df2.isnull().sum()

Make              0
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [ ]:
df2['Colour']=df2['Colour'].fillna('Orange')
df2

       Make Colour  Odometer (KM)  Doors      Price
0    Nissan  Black        10148.0    4.0  Rs1366850
1    Toyota  White        10217.0    4.0  Rs1144150
2    Toyota  White        10247.0    4.0  Rs1628300
3     Honda  White        10953.0    4.0   Rs831800
4    Nissan   Blue        10954.0    4.0  Rs1521950
..      ...    ...            ...    ...        ...
995  Toyota  White            NaN    4.0  Rs1706650
996  Toyota  White            NaN    4.0  Rs1767900
997     BMW  White            NaN    5.0  Rs1906400
998  Toyota  White            NaN    4.0        NaN
999  Toyota  White            NaN    4.0        NaN

[1000 rows x 5 columns]

In [ ]:
df2['Odometer (KM)']=df2['Odometer (KM)'].fillna(10954.0)
df2

       Make Colour  Odometer (KM)  Doors      Price
0    Nissan  Black        10148.0    4.0  Rs1366850
1    Toyota  White        10217.0    4.0  Rs1144150
2    Toyota  White        10247.0    4.0  Rs1628300
3     Honda  White        10953.0    4.0   Rs831800
4    Nissan   Blue        10954.0    4.0  Rs1521950
..      ...    ...            ...    ...        ...
995  Toyota  White        10954.0    4.0  Rs1706650
996  Toyota  White        10954.0    4.0  Rs1767900
997     BMW  White        10954.0    5.0  Rs1906400
998  Toyota  White        10954.0    4.0        NaN
999  Toyota  White        10954.0    4.0        NaN

[1000 rows x 5 columns]

In [ ]:
df2['Doors']=df2['Doors'].fillna(2)
df2

       Make Colour  Odometer (KM)  Doors      Price
0    Nissan  Black        10148.0    4.0  Rs1366850
1    Toyota  White        10217.0    4.0  Rs1144150
2    Toyota  White        10247.0    4.0  Rs1628300
3     Honda  White        10953.0    4.0   Rs831800
4    Nissan   Blue        10954.0    4.0  Rs1521950
..      ...    ...            ...    ...        ...
995  Toyota  White        10954.0    4.0  Rs1706650
996  Toyota  White        10954.0    4.0  Rs1767900
997     BMW  White        10954.0    5.0  Rs1906400
998  Toyota  White        10954.0    4.0        NaN
999  Toyota  White        10954.0    4.0        NaN

[1000 rows x 5 columns]

In [ ]:
df2['Price']=df2['Price'].fillna('Rs1906400')
df2

       Make Colour  Odometer (KM)  Doors      Price
0    Nissan  Black        10148.0    4.0  Rs1366850
1    Toyota  White        10217.0    4.0  Rs1144150
2    Toyota  White        10247.0    4.0  Rs1628300
3     Honda  White        10953.0    4.0   Rs831800
4    Nissan   Blue        10954.0    4.0  Rs1521950
..      ...    ...            ...    ...        ...
995  Toyota  White        10954.0    4.0  Rs1706650
996  Toyota  White        10954.0    4.0  Rs1767900
997     BMW  White        10954.0    5.0  Rs1906400
998  Toyota  White        10954.0    4.0  Rs1906400
999  Toyota  White        10954.0    4.0  Rs1906400

[1000 rows x 5 columns]

In [ ]:
df2.isnull().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [ ]:
# mean
df3 = df.copy()

In [ ]:
mn_odo = df3['Odometer (KM)'].mean()
mn_odo=mn_odo.round()

In [ ]:
df3['Odometer (KM)']=df3['Odometer (KM)'].fillna(mn_odo)
df3

       Make Colour  Odometer (KM)  Doors      Price
0    Nissan  Black        10148.0    4.0  Rs1366850
1    Toyota  White        10217.0    4.0  Rs1144150
2    Toyota  White        10247.0    4.0  Rs1628300
3     Honda  White        10953.0    4.0   Rs831800
4    Nissan   Blue        10954.0    4.0  Rs1521950
..      ...    ...            ...    ...        ...
995  Toyota  White       131253.0    4.0  Rs1706650
996  Toyota  White       131253.0    4.0  Rs1767900
997     BMW  White       131253.0    5.0  Rs1906400
998  Toyota  White       131253.0    4.0        NaN
999  Toyota  White       131253.0    4.0        NaN

[1000 rows x 5 columns]