In [ ]:
# pandas
# data manipulation library
# series(1D),dataframe(2D)
# EDA (Exploratory data analysis)

In [ ]:
import pandas as pd

In [ ]:
# series
data = ["hari","sonia","divya"]
y = pd.Series(data)
y

0     hari
1    sonia
2    divya
dtype: object

In [ ]:
y.shape

(3,)

In [ ]:
y.ndim

1

In [ ]:
h = pd.Series([12,13,14,15,16],index=['a','b','c','d','e'])
h

a    12
b    13
c    14
d    15
e    16
dtype: int64

In [ ]:
h.shape

(5,)

In [ ]:
h.size

5

In [ ]:
details = pd.Series(["shamna",21,"thrissur"],index = ['name','age','place'])
details

name       shamna
age            21
place    thrissur
dtype: object

In [ ]:
details.size

3

In [ ]:
details.shape

(3,)

In [ ]:
details.ndim

1

In [ ]:
details['name']

'shamna'

In [ ]:
details['age']

21

In [ ]:
# index location = iloc
details.iloc[0:]

name       shamna
age            21
place    thrissur
dtype: object

In [ ]:
details.iloc[0]

'shamna'

In [ ]:
details.iloc[1:]

age            21
place    thrissur
dtype: object

In [ ]:
# dataframe (2D) (row,column)
lst = [['sona',20,'tsr'],['alen',21,'pkd'],['edwin',22,'kochi']]
df = pd.DataFrame(lst)
df

       0   1      2
0   sona  20    tsr
1   alen  21    pkd
2  edwin  22  kochi

In [ ]:
df.ndim

2

In [ ]:
df.shape

(3, 3)

In [ ]:
df.size

9

In [ ]:
data = [[20,30],[30,40]]
df1 = pd.DataFrame(data,index = ['student1','student2'],columns = ['science','maths'])
df1

          science  maths
student1       20     30
student2       30     40

In [ ]:
import numpy as np
h = pd.Series(np.arange(2,20,3))
h

0     2
1     5
2     8
3    11
4    14
5    17
dtype: int64

In [ ]:
# list of dictionaries
list1 = [{'name':'alen','age':35,'place':'tsr'},{'name':'nandana','age':22,'place':'tsr'},{'name':'shamna','age':21,'place':'kochi'}]
df3 = pd.DataFrame(list1)
df3

      name  age  place
0     alen   35    tsr
1  nandana   22    tsr
2   shamna   21  kochi

In [ ]:
# dictionaries of list
list2 = {"name":["athira","sona","chinnu"],"age":[21,24,26],"course":["data science","django","data analytics"]}
df4 = pd.DataFrame(list2)
df4

     name  age          course
0  athira   21    data science
1    sona   24          django
2  chinnu   26  data analytics

In [ ]:
# dictionary of list
data = {"employee_id":["E001","E002","E003"," E004"],"employee_name":["arun","nandana","shwetha","gouri"],"salary":[35000,40000,54000,32000],"designation":["data entry","project manager","software developer","data analyst"]}
df5 = pd.DataFrame(data)
df5

  employee_id employee_name  salary         designation
0        E001          arun   35000          data entry
1        E002       nandana   40000     project manager
2        E003       shwetha   54000  software developer
3        E004         gouri   32000        data analyst

In [ ]:
df5["employee_id"]

0     E001
1     E002
2     E003
3     E004
Name: employee_id, dtype: object

In [ ]:
df5[["employee_id","employee_name"]]

  employee_id employee_name
0        E001          arun
1        E002       nandana
2        E003       shwetha
3        E004         gouri

In [ ]:
df5[["employee_id","employee_name","designation"]]

  employee_id employee_name         designation
0        E001          arun          data entry
1        E002       nandana     project manager
2        E003       shwetha  software developer
3        E004         gouri        data analyst

In [ ]:
df5['salary']

0    35000
1    40000
2    54000
3    32000
Name: salary, dtype: int64

In [ ]:
df5.iloc[0:2,0:1]

  employee_id
0        E001
1        E002

In [ ]:
# select the 3 rows, with column employname and designation
# using iloc
df5[["employee_name","designation"]].iloc[0:3]

  employee_name         designation
0          arun          data entry
1       nandana     project manager
2       shwetha  software developer

In [ ]:
# another method
df5.iloc[0:3,[1,3]]

  employee_name         designation
0          arun          data entry
1       nandana     project manager
2       shwetha  software developer